# Generated by Django 3.1 on 2021-08-04 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_variation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variation',
            old_name='is_available',
            new_name='is_active',
        ),
    ]
